command is /usr/bin/ssh -n -T tsinghua_yq@machine 'python ./proximaty.py'
ssh: Could not resolve hostname pli1-br-2.hpl.hp.com: Name or service not known
pli1-br-2.hpl.hp.com: 0 bytes

ssh: Could not resolve hostname pllab1.kamgu.ru: Name or service not known
pllab1.kamgu.ru: 0 bytes

ssh: Could not resolve hostname pllab2.kamgu.ru: Name or service not known
pllab2.kamgu.ru: 0 bytes

ssh: Could not resolve hostname planetlab2.aub.edu.lb: Name or service not known
planetlab2.aub.edu.lb: 0 bytes

ssh: Could not resolve hostname planetlab1.aub.edu.lb: Name or service not known
planetlab1.aub.edu.lb: 0 bytes

ssh: Could not resolve hostname planetlab2.iin-bit.com.cn: Name or service not known
planetlab2.iin-bit.com.cn: 0 bytes

planetlab5.cs.duke.edu: timed out probe

planetlab-2.rml.ryerson.ca: timed out probe

planetlab-1.vuse.vanderbilt.edu: timed out probe

ssh: Could not resolve hostname planetlab2.cs.unb.ca: Name or service not known
planetlab2.cs.unb.ca: 0 bytes

planetlab2.olsztyn.rd.tp.pl: timed out probe

planetlab-1.rml.ryerson.ca: timed out probe

Permission denied, please try again.
planetlab1.engr.ccny.cuny.edu: timed out probe

Permission denied, please try again.
ssh: Could not resolve hostname planetlab1.cs.unb.ca: Name or service not known
planetlab1.cs.unb.ca: 0 bytes

planet-lab.iki.rssi.ru: timed out probe

Permission denied (publickey,password).
pl2.bit.uoit.ca: 0 bytes

lsirextpc01.epfl.ch: timed out ssh

plab2.psgtech.ac.in: timed out probe

scratchy.cs.uga.edu: timed out probe

itchy.cs.uga.edu: timed out probe

planetlab2.engr.ccny.cuny.edu: timed out probe

planetlab1.nowogrodzka.rd.tp.pl: timed out probe

planetlab2.iitr.ernet.in: timed out probe

planetlab0.ias.csusb.edu: timed out probe

Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
pl1.bit.uoit.ca: 0 bytes

planetlab2.cse.msu.edu: timed out probe

node0.planetlab.etl.luc.edu: timed out probe

mnc2.pusan.ac.kr: timed out probe

pl2.ernet.in: timed out probe

planetlab1.cs.wayne.edu: timed out probe

ssh: Could not resolve hostname planetlab1.homelinux.org: Name or service not known
planetlab1.homelinux.org: 0 bytes

planlab1.cs.caltech.edu: timed out probe

planetlab2.cse.nd.edu: timed out probe

ssh: Could not resolve hostname planetlab2.iitb.ac.in: Name or service not known
planetlab2.iitb.ac.in: 0 bytes

ssh: Could not resolve hostname planetlab1.iitb.ac.in: Name or service not known
planetlab1.iitb.ac.in: 0 bytes

ssh: Could not resolve hostname planetlab1.iin-bit.com.cn: Name or service not known
planetlab1.iin-bit.com.cn: 0 bytes

planlab2.cs.caltech.edu: timed out probe

charon.cs.binghamton.edu: timed out probe

planetlab-2.vuse.vanderbilt.edu: timed out probe

node1.planetlab.etl.luc.edu: timed out probe

planetlab2.cs.duke.edu: timed out probe

pl2.cewit.stonybrook.edu: timed out probe

pl1.cewit.stonybrook.edu: timed out probe

planetlab2.nileu.edu.eg: timed out probe

planetlab1.nileu.edu.eg: timed out probe

planetlab2.eecs.northwestern.edu: timed out probe

planetlabnode-1.docomolabs-usa.com: timed out probe

planetlab1.simula.no: timed out probe

pluto.cs.binghamton.edu: timed out probe

planetlabnode-2.docomolabs-usa.com: timed out probe

ssh: Could not resolve hostname planetlab1.gdansk.rd.tp.pl: Name or service not known
planetlab1.gdansk.rd.tp.pl: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
ple2.ipv6.lip6.fr: 0 bytes

planetlab1.pop-ce.rnp.br: timed out probe

planetlab2.csg.uzh.ch: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.ionio.gr: 0 bytes

planetlab1.lublin.rd.tp.pl: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
ple01.fc.univie.ac.at: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pnode1.pdcc-ntu.singaren.net.sg: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab-1.pdl.nudt.edu.cn: 0 bytes

Permission denied (publickey,keyboard-interactive).
onelab3.info.ucl.ac.be: 0 bytes

Permission denied (publickey).
planetlab1.csuohio.edu: 0 bytes

peeramide.irisa.fr: 0 bytes

planetlab01.tkn.tu-berlin.de: 0 bytes

planetlab1.xeno.cl.cam.ac.uk: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.umassd.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab4.wail.wisc.edu: 0 bytes

planetlab2.koganei.wide.ad.jp: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-2.cmcl.cs.cmu.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.cs.uoregon.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-13.e5.ijs.si: 0 bytes

planetlab2.pop-ce.rnp.br: timed out ssh

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-coffee.ait.ie: 0 bytes

plab-2.sinp.msu.ru: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
ple2.tu.koszalin.pl: 0 bytes

Permission denied (publickey).
planetlab9.millennium.berkeley.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
aguila2.lsi.upc.edu: 0 bytes

planetlab1.sics.se: 0 bytes

planetlab1.lkn.ei.tum.de: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
openlab01.pl.sophia.inria.fr: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-02.kusa.ac.jp: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.di.unito.it: 0 bytes

ssh: connect to host planck249ple.test.iminds.be port 22: No route to host
planck249ple.test.iminds.be: 0 bytes

ssh: connect to host planck250ple.test.iminds.be port 22: No route to host
planck250ple.test.iminds.be: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
aguila1.lsi.upc.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
csplanetlab3.kaist.ac.kr: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.cs.uiuc.edu: 0 bytes

planetx.scs.cs.nyu.edu: timed out probe

planetlab1.hust.edu.cn: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab7.millennium.berkeley.edu: 0 bytes

planetlab1.iii.u-tokyo.ac.jp: timed out probe

Permission denied (publickey).
planetlab2.engr.uconn.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
vn4.cse.wustl.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
earth.cs.brown.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
roam2.cs.ou.edu: 0 bytes

planetlab-3.cs.ucy.ac.cy: timed out ssh

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab03.cs.washington.edu: 0 bytes

Permission denied (publickey).
kc-sce-plab2.umkc.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl1.rcc.uottawa.ca: 0 bytes

Permission denied (publickey,keyboard-interactive).
planet-lab2.ufabc.edu.br: 0 bytes

node-1.mcgillplanetlab.org: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planet-plc-3.mpi-sws.org: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pli1-pa-6.hpl.hp.com: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.singaren.net.sg: 0 bytes

subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
plab1.nec-labs.com: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
pl-dccd-02.cua.uam.mx: timed out probe

  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab4.postel.org: 0 bytes

planetlab7.csres.utexas.edu: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.iitkgp.ac.in: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-03.cs.princeton.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ricepl-2.cs.rice.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pli2-pa-2.hpl.hp.com: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2-tijuana.lan.redclara.net: 0 bytes

planetlab1.cs.ucl.ac.uk: timed out probe

planet1.scs.cs.nyu.edu: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.buaa.edu.cn: 0 bytes

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that the RSA host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
d1:9c:3f:43:f9:e0:aa:8f:4a:2f:1b:7d:28:f7:36:27.
Please contact your system administrator.
Add correct host key in /root/.ssh/known_hosts to get rid of this message.
Offending key in /root/.ssh/known_hosts:73
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
Permission denied (publickey).
pl01.comp.polyu.edu.hk: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.poly.edu: 0 bytes

    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.comp.nus.edu.sg: 0 bytes

Permission denied (publickey).
planetlab10.millennium.berkeley.edu: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab2.cs.columbia.edu: 0 bytes

Permission denied (publickey).
planetlab15.millennium.berkeley.edu: 0 bytes

ssh: connect to host planetlab1-saopaulo.lan.redclara.net port 22: No route to host
planetlab1-saopaulo.lan.redclara.net: 0 bytes

planet2.ku.edu.tr: timed out probe

planetlab1.pop-rj.rnp.br: timed out probe

planetlab2.iii.u-tokyo.ac.jp: timed out probe

of-planet5.stanford.edu: timed out probe

planetlab2.een.orst.edu: timed out probe

ssh: Could not resolve hostname planetlab2.gdansk.rd.tp.pl: Name or service not known
planetlab2.gdansk.rd.tp.pl: 0 bytes

planetlab1.een.orst.edu: timed out probe

ssh: Could not resolve hostname pli2-br-1.hpl.hp.com: Name or service not known
pli2-br-1.hpl.hp.com: 0 bytes

ssh: Could not resolve hostname pli1-br-3.hpl.hp.com: Name or service not known
pli1-br-3.hpl.hp.com: 0 bytes

ssh: Could not resolve hostname pli1-br-1.hpl.hp.com: Name or service not known
pli1-br-1.hpl.hp.com: 0 bytes

ssh: Could not resolve hostname pli2-br-2.hpl.hp.com: Name or service not known
pli2-br-2.hpl.hp.com: 0 bytes

planetlab-1.ece.iastate.edu: timed out probe

planetlab1.csie.nuk.edu.tw: timed out probe

fobos.cecalc.ula.ve: timed out probe

planetlab3.cs.uchicago.edu: timed out probe

Permission denied (publickey,keyboard-interactive).
planetlab1.bupt.edu.cn: 0 bytes

pli1-tlnx.hpl.hp.com: timed out probe

planetlab3.millennium.berkeley.edu: timed out probe

planetlab4.cs.duke.edu: timed out probe

planetlab4.singaren.net.sg: timed out probe

Permission denied (publickey,keyboard-interactive).
planetlab03.mpi-sws.mpg.de: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    Permission denied (publickey,keyboard-interactive).
planetlab1.cti.espol.edu.ec: 0 bytes

subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.eee.hku.hk: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab6.flux.utah.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.cs.otago.ac.nz: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
75-130-96-12.static.oxfr.ma.charter.com: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pl3.cs.unm.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
      File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl1.eng.monash.edu.au: 0 bytes

subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.singaren.net.sg: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-2.sysu.edu.cn: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
plgmu1.ite.gmu.edu: 0 bytes

planet1.l3s.uni-hannover.de: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
node1.planetlab.mathcs.emory.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.pop-pa.rnp.br: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.dit.upm.es: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
plab-2.diegm.uniud.it: 0 bytes

pl-dccd-01.cua.uam.mx: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planet-lab2.itba.edu.ar: 0 bytes

planetvs2.informatik.uni-stuttgart.de: timed out probe

planetlab2.csres.utexas.edu: timed out probe

planetlab1.cs.umb.edu: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
node2pl.planet-lab.telecom-lille1.eu: 0 bytes

ssh: connect to host planetlab3.csail.mit.edu port 22: Connection refused
planetlab3.csail.mit.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
flow.colgate.edu: 0 bytes

planetlab2.cs.umb.edu: timed out probe

planetlab2.citadel.edu: timed out ssh

planet2.scs.stanford.edu: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
75-130-96-13.static.oxfr.ma.charter.com: 0 bytes

planetlab01.lums.edu.pk: timed out probe

planetlab2.csie.nuk.edu.tw: timed out probe

python: can't open file './proximaty.py': [Errno 2] No such file or directory
planetlab2.upm.ro: 0 bytes

planetlab1.tmit.bme.hu: 0 bytes

planetlab1.cse.msu.edu: timed out probe

pads23.cs.nthu.edu.tw: timed out probe

planetlab4.csres.utexas.edu: timed out probe

planetlab2.lublin.rd.tp.pl: timed out probe

planetlab1.csres.utexas.edu: timed out probe

planetlab1.eecs.northwestern.edu: timed out probe

plab-1.diegm.uniud.it: timed out probe

planetlab0.ucsc.cmb.ac.lk: timed out probe

Permission denied (publickey,keyboard-interactive).
planetlab1.cs.stevens-tech.edu: 0 bytes

planetlab2.eas.asu.edu: timed out probe

ssh: connect to host planetlab2.pop-ce.rnp.br port 22: Connection timed out
planetlab1.nvlab.org: timed out probe

planetlab-2.fokus.fraunhofer.de: 0 bytes

peeramidion.irisa.fr: 0 bytes

planetlab3.csres.utexas.edu: timed out probe

planetlab1.eas.asu.edu: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.aut.ac.nz: 0 bytes

arari.snu.ac.kr: timed out probe

Permission denied, please try again.
pads21.cs.nthu.edu.tw: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-um00.di.uminho.pt: 0 bytes

Permission denied, please try again.
Permission denied (publickey,password).
nw142.csie.ncu.edu.tw: 0 bytes

planet1.scs.stanford.edu: timed out probe

'vserver ... suexec' is supported for running vservers only; aborting...
iason.inf.uth.gr: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
host2.planetlab.informatik.tu-darmstadt.de: 0 bytes

nis-planet2.doshisha.ac.jp: timed out probe

Permission denied (publickey,keyboard-interactive).
planetlab2.bupt.edu.cn: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.koganei.wide.ad.jp: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
plab4.ple.silweb.pl: 0 bytes

Permission denied (publickey,keyboard-interactive).
dannan.disy.inf.uni-konstanz.de: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab6.cs.duke.edu: 0 bytes

python: can't open file './proximaty.py': [Errno 2] No such file or directory
planetlab-1.imag.fr: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-1.sjtu.edu.cn: 0 bytes

planetlab02.dis.unina.it: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.cs.pitt.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.bgu.ac.il: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
node2.planetlab.mathcs.emory.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab6.cs.cornell.edu: 0 bytes

Permission denied (publickey).
plab1.larc.usp.br: 0 bytes

planetlab1.informatik.uni-goettingen.de: 0 bytes

planetlab2.tau.ac.il: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planet-plc-2.mpi-sws.org: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab1-tijuana.lan.redclara.net: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pl4.cs.unm.edu: 0 bytes

147-179.surfsnel.dsl.internl.net: timed out ssh

planet2.l3s.uni-hannover.de: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.fct.ualg.pt: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.ionio.gr: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planet-plc-4.mpi-sws.org: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    ssh: connect to host planet1.ku.edu.tr port 22: No route to host
planet1.ku.edu.tr: 0 bytes

subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.science.unitn.it: 0 bytes

planetlab-3.iscte.pt: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab4.cslab.ece.ntua.gr: 0 bytes

planetlab2.unineuchatel.ch: 0 bytes

uoepl1.essex.ac.uk: timed out probe

Permission denied (publickey,keyboard-interactive).
plab3.ple.silweb.pl: 0 bytes

planetlab1lannion.elibel.tm.fr: 0 bytes

'vserver ... suexec' is supported for running vservers only; aborting...
planetlab-2.di.fc.ul.pt: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.ifi.uio.no: 0 bytes

    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.ifi.uio.no: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab05.cs.washington.edu: 0 bytes

planetlab2.tmit.bme.hu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    Permission denied (publickey,keyboard-interactive).
planetlab-1.man.poznan.pl: 0 bytes

subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.pop-mg.rnp.br: 0 bytes

planetlab4.cs.st-andrews.ac.uk: 0 bytes

planetlab4.hiit.fi: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.lkn.ei.tum.de: 0 bytes

planetlab2.mta.ac.il: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
nis-planet1.doshisha.ac.jp: 0 bytes

planetlab1.cyfronet.pl: timed out probe

planetlab02.cnds.unibe.ch: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
plewifi.ipv6.lip6.fr: 0 bytes

planet1.unipr.it: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
ple2.dmcs.p.lodz.pl: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pandora.we.po.opole.pl: 0 bytes

pl3.planetlab.uvic.ca: timed out probe

Permission denied (publickey).
planetlab3.comp.nus.edu.sg: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-02.bu.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planet2.servers.ua.pt: 0 bytes

python: can't open file './proximaty.py': [Errno 2] No such file or directory
lim-planetlab-1.univ-reunion.fr: 0 bytes

Permission denied (publickey,keyboard-interactive).
dschinni.planetlab.extranet.uni-passau.de: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planet-lab-node2.netgroup.uniroma2.it: 0 bytes

    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pli2-pa-3.hpl.hp.com: 0 bytes

planetlab02.cs.tcd.ie: 0 bytes

planetlab1.aston.ac.uk: 0 bytes

thalescom-48-42.cnt.nerim.net: timed out probe

inriarennes2.irisa.fr: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planet1.servers.ua.pt: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
ple3.ipv6.lip6.fr: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
ple4.ipv6.lip6.fr: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
host1.planetlab.informatik.tu-darmstadt.de: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.cesnet.cz: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab4.williams.edu: 0 bytes

iraplab1.iralab.uni-karlsruhe.de: 0 bytes

python: can't open file './proximaty.py': [Errno 2] No such file or directory
cs-planetlab4.cs.surrey.sfu.ca: 0 bytes

planetlab6.csres.utexas.edu: timed out probe

planetlab3.hiit.fi: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.unl.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
host149-82-static.93-94-b.business.telecomitalia.it: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-1.research.netlab.hut.fi: 0 bytes

planetlab1.ics.forth.gr: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
ple02.fc.univie.ac.at: 0 bytes

planetlab2.s3.kth.se: 0 bytes

planetlab-1.iscte.pt: 0 bytes

planetlab1.exp-math.uni-essen.de: timed out ssh

planetlab2.ci.pwr.wroc.pl: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.eecs.umich.edu: 0 bytes

146-179.surfsnel.dsl.internl.net: timed out ssh

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
mercury.silicon-valley.ru: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab5.csee.usf.edu: 0 bytes

planetlab04.cnds.unibe.ch: 0 bytes

planet3.cs.huji.ac.il: 0 bytes

planetlab01.cs.tcd.ie: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.byu.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.diku.dk: 0 bytes

planetlab-4.imperial.ac.uk: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
ple6.ipv6.lip6.fr: 0 bytes

planetlab2.cs.uit.no: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-12.e5.ijs.si: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
openlab02.pl.sophia.inria.fr: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-4.cs.ucy.ac.cy: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
onelab10.pl.sophia.inria.fr: 0 bytes

iraplab2.iralab.uni-karlsruhe.de: 0 bytes

planetlab2.informatik.uni-goettingen.de: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-1.ing.unimo.it: 0 bytes

host147-82-static.93-94-b.business.telecomitalia.it: 0 bytes

planetlab1.fct.ualg.pt: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
orval.infonet.fundp.ac.be: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
onelab11.pl.sophia.inria.fr: 0 bytes

planet01.hhi.fraunhofer.de: 0 bytes

planetlab02.tkn.tu-berlin.de: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.thlab.net: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.willab.fi: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.willab.fi: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planet1.inf.tu-dresden.de: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
plab1.tidprojects.com: 0 bytes

planetlab2.urv.cat: 0 bytes

planetlab-1.cs.ucy.ac.cy: timed out ssh

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ait05.us.es: 0 bytes

  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
onelab-2.fhi-fokus.de: 0 bytes

Permission denied (publickey).
planetlab01.uncc.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
prata.mimuw.edu.pl: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
plab1.cs.msu.ru: 0 bytes

thalescom-48-41.cnt.nerim.net: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
ple1.dmcs.p.lodz.pl: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.upm.ro: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab1.di.unito.it: 0 bytes

plab2-itec.uni-klu.ac.at: timed out ssh

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl001.ece.upatras.gr: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
plab2.engr.sjsu.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planet6.cs.ucsb.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlabeu-1.tssg.org: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2lannion.elibel.tm.fr: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
lsirextpc02.epfl.ch: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.ci.pwr.wroc.pl: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.rd.tut.fi: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.rd.tut.fi: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
chimay.infonet.fundp.ac.be: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.uc3m.es: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.cs.ucla.edu: 0 bytes

subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.rutgers.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
venus.silicon-valley.ru: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.esprit-tn.com: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-2.cs.unibas.ch: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.polito.it: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.netlab.uky.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.uc3m.es: 0 bytes

planetlab-5.ece.iastate.edu: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlabpc1.upf.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.utt.fr: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
onelab7.iet.unipi.it: 0 bytes

    raise child_exception
OSError: [Errno 2] No such file or directory
planetlabeu-2.tssg.org: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.upc.es: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.esprit-tn.com: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
onelab4.warsaw.rd.tp.pl: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-2.ing.unimo.it: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.upc.es: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.eecs.jacobs-university.de: 0 bytes

ssh: connect to host planetlab1.eecs.jacobs-university.de port 22: No route to host
planetlab1.eecs.jacobs-university.de: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl002.ece.upatras.gr: 0 bytes

    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.informatik.uni-erlangen.de: 0 bytes

'vserver ... suexec' is supported for running vservers only; aborting...
wlab02.pl.sophia.inria.fr: 0 bytes

planet2.unipr.it: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
prometeusz.we.po.opole.pl: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
gschembra3.diit.unict.it: 0 bytes

planetlab-node1.it-sudparis.eu: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-1.fokus.fraunhofer.de: 0 bytes

Permission denied (publickey).
planetlab1.engr.uconn.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.di.unito.it: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-1.cs.unibas.ch: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ple2.cesnet.cz: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.di.fct.unl.pt: 0 bytes

'vserver ... suexec' is supported for running vservers only; aborting...
planetlab1.itsec.rwth-aachen.de: 0 bytes

'vserver ... suexec' is supported for running vservers only; aborting...
planetlab2.itsec.rwth-aachen.de: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planck227ple.test.ibbt.be: 0 bytes

planetlab-2.iscte.pt: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ple1.cesnet.cz: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.eecs.ucf.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.urv.cat: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.williams.edu: 0 bytes

subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.tlm.unavarra.es: 0 bytes

'vserver ... suexec' is supported for running vservers only; aborting...
planetlab2.tlm.unavarra.es: 0 bytes

planetlab1.buaa.edu.cn: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planet-plc-6.mpi-sws.org: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planet1.elte.hu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planet3.cc.gt.atl.ga.us: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
csplanetlab4.kaist.ac.kr: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab5.eecs.umich.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.cs.unc.edu: 0 bytes

planetlab-node3.it-sudparis.eu: timed out ssh

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
ttu1-1.nodes.planet-lab.org: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.cs.cornell.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.cesnet.cz: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pli1-pa-5.hpl.hp.com: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab4.tamu.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab4.inf.ethz.ch: 0 bytes

pl02.comp.polyu.edu.hk: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-n2.wand.net.nz: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.u-strasbg.fr: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.u-strasbg.fr: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab-2.ssvl.kth.se: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    Permission denied (publickey,keyboard-interactive).
planetlab5.millennium.berkeley.edu: 0 bytes

subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab05.mpi-sws.mpg.de: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-2.cs.uh.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pli1-pa-4.hpl.hp.com: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-01.bu.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planet5.cs.ucsb.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planet-lab-node1.netgroup.uniroma2.it: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 49, in <module>
    request = urllib2.urlopen("http://115.25.86.11/pong.php?ip={0}&vantage_domain={1}&bw={2}&msg={3}".format(realip, urllib2.quote(vantage_domain), bw, urllib2.quote(line) ) )
AttributeError: 'str' object has no attribute 'format'
planetlab-1.usask.ca: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
plnode-04.gpolab.bbn.com: 0 bytes

Permission denied (publickey,keyboard-interactive).
planet2.cs.rochester.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planet1.cc.gt.atl.ga.us: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.cs.uoregon.edu: 0 bytes

Permission denied (publickey).
netapp6.cs.kookmin.ac.kr: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.c3sl.ufpr.br: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab4.mini.pw.edu.pl: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
plab2.larc.usp.br: 0 bytes

ssh: connect to host planetlab1.exp-math.uni-essen.de port 22: Connection timed out
Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ricepl-4.cs.rice.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.nakao-lab.org: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.ewi.tudelft.nl: 0 bytes

Permission denied (publickey).
planetlab-2.pdl.nudt.edu.cn: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planet2.cc.gt.atl.ga.us: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
python: can't open file './proximaty.py': [Errno 2] No such file or directory
planetlab1.cs.ubc.ca: 0 bytes

    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab6.csee.usf.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.byu.edu: 0 bytes

planet-lab1.cs.ucr.edu: timed out ssh

Permission denied (publickey).
planetlab-1.cs.uh.edu: 0 bytes

Permission denied (publickey).
planetlab1.nakao-lab.org: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pli2-pa-1.hpl.hp.com: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pluto.cs.brown.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
mtuplanetlab2.cs.mtu.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.tamu.edu: 0 bytes

    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pnode2.pdcc-ntu.singaren.net.sg: 0 bytes

ssh: Could not resolve hostname plgmu5.ite.gmu.edu: Name or service not known
plgmu5.ite.gmu.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planet2.pnl.nitech.ac.jp: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planet1.pnl.nitech.ac.jp: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1-buenosaires.lan.redclara.net: 0 bytes

Permission denied (publickey).
netapp7.cs.kookmin.ac.kr: 0 bytes

planetlab-3.imperial.ac.uk: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
ttu2-1.nodes.planet-lab.org: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.inf.ethz.ch: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-1.calpoly-netlab.net: 0 bytes

planetlab2.singaren.net.sg: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
plgmu2.ite.gmu.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
mars.planetlab.haw-hamburg.de: 0 bytes

  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planet4.cc.gt.atl.ga.us: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-1.sysu.edu.cn: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.inf.ethz.ch: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planet-plc-1.mpi-sws.org: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.acis.ufl.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab4.cs.uoregon.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.tamu.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pl2.cs.unm.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-01.cs.princeton.edu: 0 bytes

planetlab1.millennium.berkeley.edu: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab4.n.info.eng.osaka-cu.ac.jp: 0 bytes

planetlab1.cs.umass.edu: 0 bytes

planetlab1.csg.uzh.ch: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab4.canterbury.ac.nz: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.temple.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab4.rutgers.edu: 0 bytes

Permission denied (publickey,keyboard-interactive).
pl1.planet.cs.kent.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-03.vt.nodes.planet-lab.org: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.eecs.northwestern.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pl1.planetlab.ics.tut.ac.jp: 0 bytes

pl2.planet.cs.kent.edu: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
plnode-03.gpolab.bbn.com: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.dojima.wide.ad.jp: 0 bytes

Permission denied (publickey).
planetlab-js1.cert.org.cn: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
vn5.cse.wustl.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
plonk.cs.uwaterloo.ca: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-n1.wand.net.nz: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.comp.nus.edu.sg: 0 bytes

subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.cs.cornell.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl1.pku.edu.cn: 0 bytes

Permission denied (publickey).
planet1.jaist.ac.jp: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab5.csail.mit.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planet-plc-5.mpi-sws.org: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
ebb.colgate.edu: 0 bytes

Permission denied (publickey).
planetlab2.csuohio.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.cti.espol.edu.ec: 0 bytes

planetlab1.diku.dk: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 49, in <module>
    request = urllib2.urlopen("http://115.25.86.11/pong.php?ip={0}&vantage_domain={1}&bw={2}&msg={3}".format(realip, urllib2.quote(vantage_domain), bw, urllib2.quote(line) ) )
AttributeError: 'str' object has no attribute 'format'
planetlab2.millennium.berkeley.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
jupiter.cs.brown.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
plab1.cs.ust.hk: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.cnds.jhu.edu: 0 bytes

recall.snu.ac.kr: timed out probe

Permission denied (publickey,keyboard-interactive).
planetlab12.millennium.berkeley.edu: 0 bytes

onelab-1.fhi-fokus.de: 0 bytes

Permission denied (publickey).
planetlab-js2.cert.org.cn: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-2.calpoly-netlab.net: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.informatik.uni-leipzig.de: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.pop-rs.rnp.br: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl2.pku.edu.cn: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.unl.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.mnlab.cti.depaul.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.cs.umass.edu: 0 bytes

python: can't open file './proximaty.py': [Errno 2] No such file or directory
cs-planetlab3.cs.surrey.sfu.ca: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.bgu.ac.il: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.mnlab.cti.depaul.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.iis.sinica.edu.tw: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pl1snu.koren.kr: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.netlab.uky.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planet-lab2.cs.ucr.edu: 0 bytes

Permission denied (publickey).
planetlab2.pop-rs.rnp.br: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.pop-mg.rnp.br: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-2.usask.ca: 0 bytes

planetlab2.pop-rj.rnp.br: timed out probe

Permission denied (publickey,keyboard-interactive).
plnode02.cs.mu.oz.au: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.informatik.uni-leipzig.de: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-2.research.netlab.hut.fi: 0 bytes

stella.planetlab.ntua.gr: 0 bytes

planetlab3.cs.st-andrews.ac.uk: 0 bytes

onelab6.iet.unipi.it: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.cs.aueb.gr: 0 bytes

planetlab1.pjwstk.edu.pl: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.eecs.umich.edu: 0 bytes

Permission denied (publickey,keyboard-interactive).
chronos.disy.inf.uni-konstanz.de: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.postel.org: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab04.cs.washington.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
ple2.ait.ac.th: 0 bytes

plab1-itec.uni-klu.ac.at: 0 bytes

planet1.cs.huji.ac.il: 0 bytes

planetlab2.cyfronet.pl: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab7.flux.utah.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
plab1.create-net.org: 0 bytes

ssh: connect to host planetlab5.flux.utah.edu port 22: Connection refused
planetlab5.flux.utah.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pln.zju.edu.cn: 0 bytes

planetlab5.csres.utexas.edu: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlabpc2.upf.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-1.cmcl.cs.cmu.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.cis.upenn.edu: 0 bytes

Permission denied (publickey).
planetlab7.csail.mit.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.um.es: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pl-node-1.csl.sri.com: 0 bytes

pl1.eecs.utk.edu: timed out probe

planetlab2.aston.ac.uk: 0 bytes

planetlab2.um.es: timed out probe

planetlab-2.imperial.ac.uk: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planet4.cs.ucsb.edu: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab2.postel.org: 0 bytes

planetlab1.cs.uit.no: 0 bytes

planetlab1.science.unitn.it: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.iis.sinica.edu.tw: 0 bytes

planetlab-2.man.poznan.pl: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.cnds.jhu.edu: 0 bytes

Permission denied (publickey).
planetlab1.unr.edu: 0 bytes

Permission denied (publickey).
planetlab2.unr.edu: 0 bytes

planetlab1.tau.ac.il: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-3.cmcl.cs.cmu.edu: 0 bytes

onelab3.warsaw.rd.tp.pl: 0 bytes

subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.cs.columbia.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.tsuniv.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-tea.ait.ie: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.ucsd.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-1.cs.colostate.edu: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab-3.dis.uniroma1.it: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab8.millennium.berkeley.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.williams.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.georgetown.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl1.yonsei.ac.kr: 0 bytes

planetlab1.cs.okstate.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl2.yonsei.ac.kr: 0 bytes

    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.uta.edu: 0 bytes

planetlab2.wiwi.hu-berlin.de: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl2.bell-labs.fr: 0 bytes

pl1.bell-labs.fr: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
node1pl.planet-lab.telecom-lille1.eu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
itchy.comlab.bth.se: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
scratchy.comlab.bth.se: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
kupl2.ittc.ku.edu: 0 bytes

planetlab-1.tagus.ist.utl.pt: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
plab2.cs.ust.hk: 0 bytes

planetlab2.xeno.cl.cam.ac.uk: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-1.cs.auckland.ac.nz: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-01.ece.uprm.edu: 0 bytes

subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab6.csail.mit.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab4.csail.mit.edu: 0 bytes

Permission denied (publickey).
planetlab13.millennium.berkeley.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetslug5.cse.ucsc.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.eecs.ucf.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.acis.ufl.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab6.goto.info.waseda.ac.jp: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab0.otemachi.wide.ad.jp: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.cs.pitt.edu: 0 bytes

planetvs1.informatik.uni-stuttgart.de: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
plab2.ple.silweb.pl: 0 bytes

planetlab2.informatik.uni-wuerzburg.de: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.jhu.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.aut.ac.nz: 0 bytes

inriarennes1.irisa.fr: 0 bytes

planetlab1.eurecom.fr: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
plab2.create-net.org: 0 bytes

planetlab02.ethz.ch: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pl2.eecs.utk.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.research.nicta.com.au: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlabtwo.ccs.neu.edu: 0 bytes

planetlab3.xeno.cl.cam.ac.uk: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.eecs.umich.edu: 0 bytes

host3-plb.loria.fr: timed out ssh

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planck228ple.test.ibbt.be: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab01.sys.virginia.edu: 0 bytes

Permission denied (publickey,keyboard-interactive).
ops.ii.uam.es: 0 bytes

planet2.zib.de: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.cnis.nyit.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pllx1.parc.xerox.com: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
plab3.eece.ksu.edu: 0 bytes

host4-plb.loria.fr: timed out ssh

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-02.vt.nodes.planet-lab.org: 0 bytes

planetlab1.cse.nd.edu: timed out probe

planet2.elte.hu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab4.cnds.jhu.edu: 0 bytes

plab1-c703.uibk.ac.at: timed out ssh

planetlab-4.ece.iastate.edu: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1-santiago.lan.redclara.net: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.thlab.net: 0 bytes

  File "./proximaty.py", line 1
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
    ^
SyntaxError: invalid syntax
planetlab1.montefiore.ulg.ac.be: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-um10.di.uminho.pt: 0 bytes

ssh: connect to host planetlab4.flux.utah.edu port 22: Connection refused
planetlab4.flux.utah.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.jhu.edu: 0 bytes

planetlab1.ewi.tudelft.nl: timed out probe

planetlab1.s3.kth.se: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
zoi.di.uoa.gr: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
kostis.di.uoa.gr: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl1.uni-rostock.de: 0 bytes

ait21.us.es: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
merkur.planetlab.haw-hamburg.de: 0 bytes

planetlab3.informatik.uni-erlangen.de: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
uoepl2.essex.ac.uk: timed out probe

    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.tamu.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pl1.csl.utoronto.ca: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
node2.planetlab.albany.edu: 0 bytes

pl1.cs.montana.edu: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
saturn.planetlab.carleton.ca: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.cs.unc.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl1.cs.yale.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-1.ida.liu.se: 0 bytes

planetlab-3.ece.iastate.edu: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-2.ida.liu.se: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab2.mini.pw.edu.pl: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planet-lab2.uba.ar: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab04.mpi-sws.mpg.de: 0 bytes

pl3.planet.cs.kent.edu: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab5.cs.cornell.edu: 0 bytes

planetlab-2.ece.iastate.edu: timed out probe

Permission denied (publickey,keyboard-interactive).
adrastea.mcs.suffolk.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.inf.ethz.ch: 0 bytes

  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.cnds.jhu.edu: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab3.arizona-gigapop.net: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab2.arizona-gigapop.net: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.cs.vu.nl: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.ntu.nodes.planet-lab.org: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planet11.csc.ncsu.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.just.edu.jo: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
dfn-ple1.x-win.dfn.de: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.cs.vu.nl: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2-saopaulo.lan.redclara.net: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.sics.se: 0 bytes

vicky.planetlab.ntua.gr: 0 bytes

onelab2.warsaw.rd.tp.pl: 0 bytes

planetlab2.eee.hku.hk: timed out ssh

Permission denied (publickey,keyboard-interactive).
planetlab1.arizona-gigapop.net: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.otemachi.wide.ad.jp: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
plnodeb.plaust.edu.cn: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.cs.purdue.edu: 0 bytes

planetlab2.cs.uoi.gr: 0 bytes

planet02.hhi.fraunhofer.de: 0 bytes

  File "./proximaty.py", line 1
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
    ^
SyntaxError: invalid syntax
planetlab2.montefiore.ulg.ac.be: 0 bytes

planetlab1.unineuchatel.ch: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-2.elisa.cpsc.ucalgary.ca: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.cqupt.edu.cn: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.cs.colorado.edu: 0 bytes

planetlab-1.webedu.ccu.edu.tw: timed out probe

planet2.inf.tu-dresden.de: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
plab4.eece.ksu.edu: 0 bytes

planetlab1.fri.uni-lj.si: 0 bytes

planetlab2.ics.forth.gr: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab5.williams.edu: 0 bytes

planetlab2.exp-math.uni-essen.de: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.wiwi.hu-berlin.de: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
rochefort.infonet.fundp.ac.be: 0 bytes

planetlab1.informatik.uni-wuerzburg.de: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.csee.usf.edu: 0 bytes

planetlab-node-01.ucd.ie: 0 bytes

planetlab2.pjwstk.edu.pl: 0 bytes

planetlab-4.iscte.pt: 0 bytes

Permission denied (publickey,keyboard-interactive).
onelab1.info.ucl.ac.be: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
ple1.ait.ac.th: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab3.bupt.edu.cn: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.mta.ac.il: 0 bytes

'vserver ... suexec' is supported for running vservers only; aborting...
medea.inf.uth.gr: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.cs.ucla.edu: 0 bytes

planetlab-2.tagus.ist.utl.pt: 0 bytes

gschembra4.diit.unict.it: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.ecs.vuw.ac.nz: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
  File "./proximaty.py", line 1    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2-santiago.lan.redclara.net: 0 bytes

onelab2.info.ucl.ac.be: 0 bytes


    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab02.just.edu.jo: 0 bytes

planetlab1.polito.it: timed out ssh

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab01.alucloud.com: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab01.ethz.ch: 0 bytes

righthand.eecs.harvard.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl1.sos.info.hiroshima-cu.ac.jp: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.williams.edu: 0 bytes

Permission denied (publickey).
planetlab11.millennium.berkeley.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
dplanet2.uoc.edu: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab16.millennium.berkeley.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.ecs.vuw.ac.nz: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab4.csee.usf.edu: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab2.cs.ucl.ac.uk: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.extern.kuleuven.be: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab4.eecs.umich.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.extern.kuleuven.be: 0 bytes

planetlab1.cs.uoi.gr: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.mini.pw.edu.pl: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
nodeb.howard.edu: 0 bytes

    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-1.cse.ohio-state.edu: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab2.sfc.wide.ad.jp: 0 bytes

planetlab02.lums.edu.pk: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab5.cs.uiuc.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab7.cs.duke.edu: 0 bytes

Read from socket failed: Connection reset by peer
  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.cs.otago.ac.nz: 0 bytes

planetlab-2.cs.uic.edu: timed out probe

planet-lab1.uba.ar: timed out probe

planetlab1.utep.edu: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.rutgers.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl1.ccsrfi.net: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.clemson.edu: 0 bytes

pl2.ccsrfi.net: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.clemson.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.cs.okstate.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.pop-pa.rnp.br: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
kupl1.ittc.ku.edu: 0 bytes

planet-lab1.itba.edu.ar: timed out ssh

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.cis.upenn.edu: 0 bytes

Permission denied (publickey,keyboard-interactive).
node1.lbnl.nodes.planet-lab.org: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planet1.dsp.ac.cn: 0 bytes

Permission denied (publickey,keyboard-interactive).
node2.lbnl.nodes.planet-lab.org: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl2.zju.edu.cn: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl2.eng.monash.edu.au: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planet0.jaist.ac.jp: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-1.ssvl.kth.se: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.cqupt.edu.cn: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.ucsd.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
osiris.planetlab.cs.umd.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.umassd.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab4.cs.uiuc.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl2.sos.info.hiroshima-cu.ac.jp: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.cnis.nyit.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.cs.uoregon.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.uta.edu: 0 bytes

whitefall.planetlab.cs.umd.edu: timed out probe

pl2.cs.montana.edu: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-5.eecs.cwru.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
miranda.planetlab.cs.umd.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.sfc.wide.ad.jp: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.iitkgp.ac.in: 0 bytes

  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.georgetown.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-1.elisa.cpsc.ucalgary.ca: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
utet.ii.uam.es: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
plab3.cs.msu.ru: 0 bytes

    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.rutgers.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
dplanet1.uoc.edu: 0 bytes

python: can't open file './proximaty.py': [Errno 2] No such file or directory
planetlab-2.imag.fr: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.upc.es: 0 bytes

python: can't open file './proximaty.py': [Errno 2] No such file or directory
lim-planetlab-2.univ-reunion.fr: 0 bytes

planetlab-1.imperial.ac.uk: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab2.cs.stevens-tech.edu: 0 bytes

node-2.mcgillplanetlab.org: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab5.goto.info.waseda.ac.jp: 0 bytes

planetlab02.sys.virginia.edu: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
planetlab3.cse.nd.edu: timed out probe

  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pl2.ucs.indiana.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.dtc.umn.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-04.vt.nodes.planet-lab.org: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planet2.dsp.ac.cn: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-6.ece.iastate.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlabone.ccs.neu.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab02.alucloud.com: 0 bytes

planetlab1.utt.fr: timed out ssh

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.cs.uml.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pub1-s.ane.cmc.osaka-u.ac.jp: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.cs.du.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planet12.csc.ncsu.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
onelab1.warsaw.rd.tp.pl: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.dtc.umn.edu: 0 bytes

  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
nodea.howard.edu: 0 bytes

python: can't open file './proximaty.py': [Errno 2] No such file or directory
planetlab2.cs.ubc.ca: 0 bytes

Permission denied (publickey,keyboard-interactive).
planet1.cs.rochester.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.wail.wisc.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pl1.planetlab.uvic.ca: 0 bytes

ssh: Could not resolve hostname server2.planetlab.iit-tech.net: Temporary failure in name resolution
server2.planetlab.iit-tech.net: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
roam1.cs.ou.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pub2-s.ane.cmc.osaka-u.ac.jp: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetslug4.cse.ucsc.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.utdallas.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
jupiter.planetlab.carleton.ca: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.poly.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.eecs.wsu.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ricepl-5.cs.rice.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl1.cis.uab.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.temple.edu: 0 bytes

    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.ustc.edu.cn: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.hust.edu.cn: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.jcp-consult.net: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab01.dis.unina.it: 0 bytes

planetlab-2.cse.ohio-state.edu: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetslug7.cse.ucsc.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab02.mpi-sws.mpg.de: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pllx2.parc.xerox.com: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pl1.ucs.indiana.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab01.cs.washington.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl2.6test.edu.cn: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
lefthand.eecs.harvard.edu: 0 bytes

plgmu3.ite.gmu.edu: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab02.cs.washington.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.utdallas.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-2.cs.colostate.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.jcp-consult.net: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.di.fct.unl.pt: 0 bytes

plgmu4.ite.gmu.edu: timed out probe

Permission denied (publickey).
planetlab1.ustc.edu.cn: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
plab2.nec-labs.com: 0 bytes

Permission denied (publickey,keyboard-interactive).
metis.mcs.suffolk.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
salt.planetlab.cs.umd.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.cslab.ece.ntua.gr: 0 bytes

plab-1.sinp.msu.ru: timed out probe

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-2.sjtu.edu.cn: 0 bytes

planet1.zib.de: timed out probe

python: can't open file './proximaty.py': [Errno 2] No such file or directory
aladdin.planetlab.extranet.uni-passau.de: 0 bytes

planetlab1.hiit.fi: timed out probe

planetlab2.hiit.fi: timed out probe

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab3.csee.usf.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
orbpl1.rutgers.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.cs.purdue.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-02.ece.uprm.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
orbpl2.rutgers.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1092, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-4.dis.uniroma1.it: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
roti.mimuw.edu.pl: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pl-node-0.csl.sri.com: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl2.cs.yale.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab6.cs.uiuc.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pl2.csl.utoronto.ca: 0 bytes

planetlab-04.cs.princeton.edu: timed out probe

Permission denied (publickey,keyboard-interactive).
planetlab1.csee.usf.edu: 0 bytes

plab1.engr.sjsu.edu: timed out probe

ssh: connect to host marie.iet.unipi.it port 22: No route to host
marie.iet.unipi.it: 0 bytes

planetlab4.cse.nd.edu: timed out probe

planetlab2.fri.uni-lj.si: 0 bytes

Permission denied (publickey).
planetlab2-buenosaires.lan.redclara.net: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planet3.cs.ucsb.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl2.uni-rostock.de: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl2.rcc.uottawa.ca: 0 bytes

planetlab2.utep.edu: timed out probe

Permission denied (publickey,keyboard-interactive).
plnode01.cs.mu.oz.au: 0 bytes

planetlab1.citadel.edu: timed out ssh

planetlab1.mini.pw.edu.pl: 0 bytes

plab2-c703.uibk.ac.at: timed out ssh

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
mtuplanetlab1.cs.mtu.edu: 0 bytes

planetlab-node-02.ucd.ie: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab4.goto.info.waseda.ac.jp: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl1.6test.edu.cn: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab1.cs.uml.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-2.cs.auckland.ac.nz: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-2.webedu.ccu.edu.tw: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab-01.vt.nodes.planet-lab.org: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
plink.cs.uwaterloo.ca: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pl2snu.koren.kr: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab3.canterbury.ac.nz: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab2.c3sl.ufpr.br: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.ucsd.edu: 0 bytes

ssh: Could not resolve hostname server4.planetlab.iit-tech.net: Temporary failure in name resolution
server4.planetlab.iit-tech.net: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ricepl-1.cs.rice.edu: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab2.eecs.wsu.edu: 0 bytes

Permission denied (publickey,keyboard-interactive).
planetlab3.postel.org: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
pl2.cis.uab.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pl2.planetlab.ics.tut.ac.jp: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab-4.eecs.cwru.edu: 0 bytes

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
planetlab2.tsuniv.edu: 0 bytes

Traceback (most recent call last):
  File "./proximaty.py", line 12, in <module>
    subp = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.5/subprocess.py", line 593, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1079, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
planetlab1.fit.vutbr.cz: 0 bytes

plnodea.plaust.edu.cn: timed out probe

planetlab1.cs.colorado.edu: timed out probe

planetlab1.cs.du.edu: timed out ssh

  File "./proximaty.py", line 1
    You are trying to use a node of the CoDeeN CDN Network. Numerical hostnames are not allowed. 
          ^
SyntaxError: invalid syntax
ssh_exchange_identification: read: Connection reset by peer
